// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Butaca
{
    public int IdButaca { get; set; }

    public string Numero { get; set; }

    public virtual ICollection<DetallesTicket> DetallesTickets { get; set; } = new List<DetallesTicket>();

    public virtual ICollection<Reservada> Reservada { get; set; } = new List<Reservada>();
}