// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class DetallesTicket
{
    public int IdDetalle { get; set; }
    public int IdTicket { get; set; }
    public int? IdFuncion { get; set; }
    public int? IdButaca { get; set; }
    public decimal? PrecioVenta { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }
    public virtual Funcione IdFuncionNavigation { get; set; }
}