// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Nacionalidade
{
    public int IdNacionalidad { get; set; }

    public string Nacionalidad { get; set; }

    public virtual ICollection<Actore> Actores { get; set; } = new List<Actore>();

    public virtual ICollection<Directore> Directores { get; set; } = new List<Directore>();
}