// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Promocione
{
    public int IdPromocion { get; set; }

    public DateTime? FechaDesde { get; set; }

    public DateTime? FechaHasta { get; set; }

    public int? ProcentajeDescuento { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}