// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Reservada
{
    public int IdReserva { get; set; }

    public int? IdButaca { get; set; }

    public int? IdFuncion { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }
}