// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int? IdTipoDoc { get; set; }

    public int? Documento { get; set; }

    public DateTime? FechaNac { get; set; }

    public int? IdBarrio { get; set; }

    public int? IdCargo { get; set; }

    public DateTime? FechaAlta { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual Cargo IdCargoNavigation { get; set; }

    public virtual TiposDoc IdTipoDocNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}