// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Horario
{
    public int IdHorario { get; set; }

    public DateTime? Horario1 { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}