// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string Titulo { get; set; }

    public int? Duracion { get; set; }

    public string Sinopsis { get; set; }

    public int? IdClasificacion { get; set; }

    public int? IdGenero { get; set; }

    public int? IdIdioma { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual Clasificacione IdClasificacionNavigation { get; set; }

    public virtual Genero IdGeneroNavigation { get; set; }

    public virtual Idioma IdIdiomaNavigation { get; set; }

    public virtual ICollection<PeliculasActore> PeliculasActores { get; set; } = new List<PeliculasActore>();

    public virtual ICollection<PeliculasDirectore> PeliculasDirectores { get; set; } = new List<PeliculasDirectore>();
}