// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class PeliculasDirectore
{
    public int IdPeliculaDirect { get; set; }

    public int? IdPelicula { get; set; }

    public int? IdDirector { get; set; }

    public virtual Directore IdDirectorNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }
}