// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineTPIProgII.Models;

public partial class Ticket
{
    public int IdTicket { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdCliente { get; set; }

    public int? IdEmpleado { get; set; }

    public int? IdMedioPedido { get; set; }

    public int? IdPromocion { get; set; }

    public int? IdFormaPago { get; set; }

    public decimal? Total { get; set; }

    public bool? Estado { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual MediosPedido IdMedioPedidoNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }

    public virtual ICollection<DetallesTicket> DetallesTicket { get; set; } = new List<DetallesTicket>();
}